from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.verify, name='verify'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path("kyc/pdf/<int:user_id>/", views.download_kyc_pdf, name="download_kyc_pdf"),
    path("kyc/email/<int:user_id>/", views.send_kyc_email, name="send_kyc_email"),
    path('verify-email/<signed_value>/', views.verify_email, name='verify_email'),
    path('blog/', views.blog, name='blog'),
    path('admin/loans/',views.manage_loans, name='manage_loans'),
    path('admin/loans/approve/<int:loan_id>/', views.approve_loan, name='approve_loan'),
    path('admin/loans/reject/<int:loan_id>/', views.reject_loan, name='reject_loan'),
    path('apply-loan/', views.apply_loan, name='apply_loan'),
    path('loan-review/', views.loan_review, name='loan_review'),
    path('loan-pending/', views.loan_pending, name='loan_pending'),
    path('loan-approved/<int:loan_id>/', views.loan_approved, name='loan_approved'),
    path('submit-loan/', views.submit_loan, name='submit_loan'),
    path('contact/', views.contact, name='contact'),
    path('detail/', views.detail, name='detail'),
    path('feature/', views.feature, name='feature'),
    path('price/', views.price, name='price'),
    path('quote/', views.quote, name='quote'),
    path('loans/', views.loans, name='loans'),
    path('kyc/', views.kyc, name='kyc'),
    path('service/', views.service, name='service'),
    path('investment/plans/', views.investment_plans, name='investment_plans'),
    path('investment/create/', views.create_investment, name='create_investment'),
    path('investment/dashboard/', views.investment_dashboard, name='investment_dashboard'),
    path('investment/detail/<int:investment_id>/', views.investment_detail, name='investment_detail'),
    path('team/', views.team, name='team'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('LogOut/', views.LogOut, name='LogOut'),
    path('reset_profile/', views.reset_profile, name='reset_profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('crypto/', views.crypto, name='crypto'),
    path('paypal/', views.paypal, name='paypal'),
    path('linking_view/', views.linking_view, name='linking_view'),
    path('profile/', views.profile, name='profile'),
    path('Upgrade_Account/', views.Upgrade_Account, name='Upgrade_Account'),
    path('tac/', views.tac, name='tac'),
    path('vat/', views.vat, name='vat'),
    path('imf/', views.imf, name='imf'),
    path('pending/', views.pending, name='pending'),
    path('bank_transfer/', views.bank_transfer, name='bank_transfer'),
]
