"""
Django settings for bank_site project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
SUPERUSER_EMAIL = 'skylinebank@gmail.com'
SUPERUSER_PASSWORD = 'Me12sleep'
import os
from pathlib import Path
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api



## Change this:
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# To either:
BASE_DIR = Path(__file__).resolve().parent.parent

# OR keep as string but use os.path.join:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.qrcpbwlscndulbuigtmz',
        'PASSWORD': '959AXvskY1wwRah9',  # Replace with your actual password
        'HOST': 'aws-1-us-west-1.pooler.supabase.com',
        'PORT': '6543',
        'OPTIONS': {
            # Disable server-side cursors to avoid PREPARE statement issues
            'options': '-c default_transaction_read_only=off',
            'client_encoding': 'UTF8',
        },
        'CONN_MAX_AGE': 600,  # Optional: connection persistence in seconds
    }
}

cloudinary.config(
    cloud_name="dlzn0moho",
    api_key="563396395915366",
    api_secret="pCSSrLNvxfFSEzY4ZnaOiF5u93o"
)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-os%ceh%!b_zte(60bvi9)pujn1v#lyuh^u4l!hr+_-5)rmf&9-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'skybridgefinance.online',
    'www.skybridgefinance.online',
    'skybridge-finance.fly.dev',
]

CSRF_TRUSTED_ORIGINS = ['https://skybridgefinance.online',
                        'https://www.skybridgefinance.online',
                        'https://www.skybridgefinance.online'
                        ]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'cloudinary',
    'cloudinary_storage',  
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'BankApp',
    'django_use_email_as_username.apps.DjangoUseEmailAsUsernameConfig',
    'custom_user.apps.CustomUserConfig',
    'django.contrib.humanize',
]

# In your settings.py file
AUTH_USER_MODEL = 'custom_user.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'bank_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'BankApp.context_processors.site_icons',
            ],
        },
    },
]

WSGI_APPLICATION = 'bank_site.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# URL to use when referring to static files
STATIC_URL = 'static/'

# Directory where collectstatic will collect static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Optional: additional directories to look for static files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

if not DEBUG:
    # Production: use WhiteNoise for serving static files
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    # Development: use default storage (or Cloudinary if desired)
    STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'
    pass

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Main static directory
    os.path.join(BASE_DIR, 'static', 'js'),  # Directory for JavaScript files
    os.path.join(BASE_DIR, 'static', 'img'),  # Directory for SASS files
    os.path.join(BASE_DIR, 'static', 'css'),  # Directory for compiled CSS files
    os.path.join(BASE_DIR, 'static', 'lib'),
    os.path.join(BASE_DIR, 'static', 'lib', 'animate'),
    os.path.join(BASE_DIR, 'static', 'lib', 'counterup'),
    os.path.join(BASE_DIR, 'static', 'lib', 'easing'),
    os.path.join(BASE_DIR, 'static', 'lib', 'owlcarousel'),
    os.path.join(BASE_DIR, 'static', 'lib', 'owlcarousel', 'assets'),
    os.path.join(BASE_DIR, 'static', 'lib', 'waypoints'),
    os.path.join(BASE_DIR, 'static', 'lib', 'wow'),
    # Add more directories if needed
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sskybridge513@gmail.com'
EMAIL_HOST_PASSWORD = 'fket lmyj nciu ovrc'
DEFAULT_FROM_EMAIL = 'Skybridge Bank <sskybridge513@gmail.com>'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
