# Generated by Django 5.1.1 on 2025-12-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
