# Generated by Django 6.0.1 on 2026-01-08 05:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front', models.FileField(upload_to='kyc/')),
                ('id_back', models.FileField(upload_to='kyc/')),
                ('selfie', models.FileField(upload_to='kyc/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(100)])),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan'), ('education', 'Education Loan'), ('medical', 'Medical Loan'), ('debt_consolidation', 'Debt Consolidation'), ('emergency', 'Emergency Loan'), ('home_improvement', 'Home Improvement'), ('other', 'Other')], default='personal', max_length=50)),
                ('purpose', models.CharField(choices=[('debt_consolidation', 'Debt Consolidation'), ('home_improvement', 'Home Improvement'), ('medical_expenses', 'Medical Expenses'), ('education_fees', 'Education/Tuition Fees'), ('business_expansion', 'Business Expansion'), ('vehicle_purchase', 'Vehicle Purchase'), ('wedding', 'Wedding Expenses'), ('travel', 'Travel/Vacation'), ('emergency', 'Emergency Funds'), ('other', 'Other')], default='other', max_length=50)),
                ('repayment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)])),
                ('interest', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], default='employed', max_length=30)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('collateral', models.TextField(blank=True, null=True)),
                ('requested_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_disbursement_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
