# Generated by Django 5.1.1 on 2025-12-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0002_userprofile_is_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_email_verified",
        ),
    ]
