# Generated by Django 5.2.10 on 2026-02-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0003_alter_userprofile_balance_alter_userprofile_savings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmentplan",
            name="interest_rate",
        ),
        migrations.RemoveField(
            model_name="userinvestment",
            name="expected_return",
        ),
        migrations.AddField(
            model_name="investmentplan",
            name="interval_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investmentplan",
            name="investment_type",
            field=models.CharField(
                choices=[
                    ("SHORT_TERM", "Short Term Trading"),
                    ("LONG_TERM", "Long Term Investment"),
                ],
                default="SHORT_TERM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="investmentplan",
            name="max_profit_percentage",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="investmentplan",
            name="min_profit_percentage",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="userinvestment",
            name="actual_return",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="userinvestment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinvestment",
            name="max_expected_return",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="userinvestment",
            name="min_expected_return",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("STARTER", "Starter Plan"),
                    ("PRO", "Pro Plan"),
                    ("ELITE", "Elite Plan"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userinvestment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
