# Generated by Django 5.1.1 on 2025-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0003_remove_userprofile_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
