# Generated by Django 5.1.1 on 2025-12-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0004_userprofile_is_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
