# Generated by Django 5.1.1 on 2025-12-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0007_kyc_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal Loan"),
                    ("business", "Business Loan"),
                    ("mortgage", "Mortgage"),
                    ("auto", "Auto Loan"),
                    ("education", "Education Loan"),
                    ("medical", "Medical Loan"),
                    ("debt_consolidation", "Debt Consolidation"),
                    ("payday", "Short-term/Payday Loan"),
                    ("other", "Other"),
                ],
                default="personal",
                max_length=50,
            ),
        ),
    ]
