# Generated by Django 5.1.1 on 2025-12-30 16:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0008_alter_loan_loan_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="annual_income",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="collateral",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("employed", "Employed"),
                    ("self_employed", "Self-Employed"),
                    ("unemployed", "Unemployed"),
                    ("student", "Student"),
                    ("retired", "Retired"),
                ],
                default="employed",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="expected_disbursement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("debt_consolidation", "Debt Consolidation"),
                    ("home_improvement", "Home Improvement"),
                    ("medical_expenses", "Medical Expenses"),
                    ("education_fees", "Education/Tuition Fees"),
                    ("business_expansion", "Business Expansion"),
                    ("vehicle_purchase", "Vehicle Purchase"),
                    ("wedding", "Wedding Expenses"),
                    ("travel", "Travel/Vacation"),
                    ("emergency", "Emergency Funds"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="repayment_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("biweekly", "Bi-weekly"),
                    ("weekly", "Weekly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="requested_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="duration",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(360),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal Loan"),
                    ("business", "Business Loan"),
                    ("mortgage", "Mortgage"),
                    ("auto", "Auto Loan"),
                    ("education", "Education Loan"),
                    ("medical", "Medical Loan"),
                    ("debt_consolidation", "Debt Consolidation"),
                    ("emergency", "Emergency Loan"),
                    ("home_improvement", "Home Improvement"),
                    ("other", "Other"),
                ],
                default="personal",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
